<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"></ul></div>

In [49]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import MinMaxScaler

In [46]:
df = pd.read_csv("../00-data/portfolio_data/2021/portfolio_jan2021.csv")
df

,date,tags,ticker,volume,pos_mean,pos_median,pos_min,pos_max,neg_mean,neg_median,...,net_median,net_min,net_max,read_score,same_day_raw,next_day_raw,sp_avg_return,next_day_sp,same_day_relative,next_day_relative
0,2021-01-04,A,A,2.0,0.110000,0.000000,0.0,1.000000,0.015000,0.0,...,0.000000,-0.500000,1.000000,0.217502,0.252231,-0.953746,1.933110,-1.031859,-1.680879,0.135142
1,2021-01-04,AAL,AAL,1.0,0.100000,0.000000,0.0,1.000000,0.030000,0.0,...,0.000000,-1.000000,1.000000,0.149566,4.542587,-3.418231,1.933110,-1.031859,2.609477,-2.073725
2,2021-01-04,AAPL,AAPL,21.0,0.111429,0.000000,0.0,0.851429,0.122381,0.0,...,0.000000,-0.672857,0.851429,0.269487,3.078190,-1.644810,1.933110,-1.031859,1.145081,-0.064243
3,2021-01-04,ABBV,ABBV,5.0,0.034000,0.000000,0.0,0.600000,0.048000,0.0,...,0.000000,-0.600000,0.600000,0.243894,1.651424,-1.034054,1.933110,-1.031859,-0.281686,1.948018
4,2021-01-04,ABT,ABT,4.0,0.312500,0.115000,0.0,1.000000,0.015000,0.0,...,0.115000,-0.247500,1.000000,0.409763,0.383455,-1.479101,1.933110,-1.031859,-1.549655,0.236260
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9821,2021-01-29,YUM,YUM,2.2,0.295500,0.199333,0.0,0.985000,0.028667,0.0,...,0.197333,-0.462667,0.985000,0.362005,0.587715,-0.802034,1.388965,-0.469278,-0.801250,1.773387
9822,2021-01-29,ZBH,ZBH,2.0,0.263333,0.000000,0.0,0.766667,0.079000,0.0,...,0.000000,-0.766667,0.766667,0.345520,1.493591,0.626332,1.388965,-0.469278,0.104626,0.192627
9823,2021-01-29,ZBRA,ZBRA,0.8,0.017500,0.000000,0.0,0.100000,0.023000,0.0,...,0.000000,-0.222000,0.100000,0.112321,0.635395,-1.445087,1.388965,-0.469278,-0.753570,-1.527676
9824,2021-01-29,ZION,ZION,0.0,0.000000,0.000000,0.0,0.000000,0.000000,0.0,...,0.000000,0.000000,0.000000,0.000000,2.539196,-0.607700,1.388965,-0.469278,1.150231,-1.288998
9825,2021-01-29,ZTS,ZTS,0.4,0.024000,0.000000,0.0,0.200000,0.000000,0.0,...,0.000000,0.000000,0.200000,0.077671,0.899450,0.396924,1.388965,-0.469278,-0.489515,1.747358

In [59]:
def daily_turnover(df, bin_size):
    # date list
    date_list = []
    # portfolio returns
    total_return = []
    # S&P 500 return
    sp_return = []
    
    # create aggregate features
    agg_cols = ['volume', 
#                 'pos_mean', 'pos_median', 'pos_min',
#        'pos_max', 'neg_mean', 'neg_median', 'neg_min', 'neg_max', 'neu_mean',
#        'neu_median', 'neu_min', 'neu_max', 
                'net_mean', 'net_median', 'net_min',
       'net_max', 'read_score']
    # scale score features
    scaler = MinMaxScaler()
    scaled_df = scaler.fit_transform(df[agg_cols].to_numpy())
    scaled_df = pd.DataFrame(scaled_df, columns=agg_cols)
    # aggregate features
    scaled_df['agg_score'] = scaled_df[agg_cols].mean(axis=1)
    scaled_df = scaled_df.drop(agg_cols,axis=1)
    # join and drop original columns
    agg_df = df.join(scaled_df).drop(agg_cols,axis=1)
    
    # sort by agg_score for each date
    sorted_df = agg_df.groupby("date").apply(lambda x: x.sort_values("agg_score", ascending=False)).reset_index(drop=True)
    # find unique dates
    date_vals = df.date.unique()
    
    # lists for top and bottom
    top_list = []
    bottom_list = []
    
    for date in date_vals:
        # set bin lengths
        bin_len = len(sorted_df[sorted_df.date == date])//bin_size

        # create top bin for long position
        top_ticks = sorted_df[sorted_df.date == date].head(bin_len)['ticker']
        top_list.append(top_ticks)

        # create bottom bin to short
        bottom_ticks = sorted_df[sorted_df.date == date].tail(bin_len)['ticker']
        bottom_list.append(bottom_ticks)

        # append dates
        date_list.append(date)
    
    return(top_list, bottom_list, date_list)

In [9]:
top = df.head()['ticker'].unique()
top

array(['A', 'AAL', 'AAPL', 'ABBV', 'ABT'], dtype=object)

In [19]:
bot = np.array(['A', 'AAL', 'AAPL', "TSLA", "AMZN"])#df.tail()['ticker'].unique()
bot

array(['A', 'AAL', 'AAPL', 'TSLA', 'AMZN'], dtype='<U4')

In [17]:
len(list(set(bot) - set(top))) / (len(top)+len(bot))

0.1111111111111111

In [45]:
lst=[]
lst.append(top)
lst.append(bot)
np.unique(lst[0])

5

In [63]:
top_list, bottom_list, date_list = daily_turnover(df,3)

In [66]:
top_to = []
bottom_to = []
to_list = []
#for i in range(len(top_list)):
for i in range(5):
    # calculate top turnover
    top_n = top_list[i] # day n
    top_n1 = top_list[i+1] # day n+1
    
    diff = len(list(set(top_n1) - set(top_n))) # stocks in n+1 not in n
    total = len(top_n)+len(top_n1)
    to = round(diff/total,2)
    to_list.append(to)

In [67]:
to_list

[0.2, 0.19, 0.23, 0.19, 0.26]