In [1]:
import pandas as pd
import time, datetime
import multiprocessing as mp
from datetime import datetime as dt

# Load data

In [6]:
bad_cols = [0,2,6,15,16,17,18,19,20,21,22,24,25,26] # unnecessary columns from example_data notebook
cols = list(range(0,26)) # list of all columns
good_cols = [i for i in cols if i not in bad_cols] # create list of useful columns
good_cols = [str(x) for x in good_cols] # convert to string
good_cols

['1', '3', '4', '5', '7', '8', '9', '10', '11', '12', '13', '14', '23']

In [7]:
start = time.time()
# read data in chunks of 100k rows at a time
chunk = pd.read_csv('feb2021.csv.zip', 
                    chunksize=100000, 
                    dtype={'3': 'str'}) # specify index column
# iter_csv = pd.read_csv('file.csv', iterator=True, chunksize=1000)
# df = pd.concat([chunk[chunk['field'] > constant] for chunk in iter_csv])
df = pd.concat(chunk) # concat chunks together
end = time.time()
print("Read csv with chunks: ",(end-start),"sec")

Read csv with chunks:  7.836688041687012 sec

In [8]:
df

,1,3,4,5,7,8,9,10,11,12,13,14,23
0,20210201000000.0,tass.com,https://tass.com/emergencies/1250941,NaN,TAX_FNCACT;TAX_FNCACT_CHILDREN;ARREST;CRISISLE...,"SOC_POINTSOFINTEREST_POLICE_STATIONS,314;TAX_F...","4#Moscow, Moskva, Russia#RS#RS48#55.7522#37.61...","4#Moscow, Moskva, Russia#RS#RS48#25106#55.7522...",olga yaroslavskaya,"Olga Yaroslavskaya,180",NaN,NaN,"Rights Commissioner Olga Yaroslavskaya,169"
1,20210201000000.0,observer-reporter.com,https://observer-reporter.com/publications/shl...,NaN,GENERAL_HEALTH;HEALTH_PANDEMIC;WB_635_PUBLIC_H...,"MANMADE_DISASTER_IMPLIED,1548;MANMADE_DISASTER...",1#Lebanon#LE#LE#33.833333#35.833333#LE,1#Lebanon#LE#LE##33.833333#35.833333#LE#2280,lindsey bricker,"Lindsey Bricker,1968",NaN,NaN,"Lindsey Bricker,2111;Sugar Sugar Scrub,2146;Me..."
2,20210201000000.0,jordantimes.com,http://jordantimes.com/news/local/ujs-css-tops...,NaN,EDUCATION;SOC_POINTSOFINTEREST;SOC_POINTSOFINT...,"TAX_FNCACT_DIRECTOR,1343;USPEC_POLICY1,769;USP...","4#Amman, (Jo11), Jordan#JO#JO11#31.95#35.9333#...",1#Jordan#JO#JO##31#36#JO#13;1#Jordan#JO#JO##31...,zaid eyadat,"Zaid Eyadat,1355",centre for strategic studies;university of jor...,"Centre For Strategic Studies,85;University Of ...","Strategic Studies,79;Middle East,231;North Afr..."
3,20210201000000.0,apnews.com,https://apnews.com/1ce7ac194ff97c882f2fe79eebb...,NaN,TAX_DISEASE;TAX_DISEASE_CANCER;WB_1406_DISEASE...,"MANMADE_DISASTER_RADIOACTIVE,975;ARMEDCONFLICT...","2#California, United States#US#USCA#36.17#-119...","3#Los Angeles, California, United States#US#US...",padraig duignan;frances gulland,"Padraig Duignan,2156;Frances Gulland,1230",u s marine mammal commission;university of cal...,"University Of California,1259;Marine Mammal Ce...","Los Angeles Times,361;Marine Mammal Center,515..."
4,20210201000000.0,wdiy.org,https://www.wdiy.org/post/hilton-valentine-fou...,NaN,NaN,NaN,"4#North Shields, North Tyneside, United Kingdo...","5#Northumberland, Northumberland, United Kingd...",chas chandler;alan price;bo diddley;germaine v...,"Chas Chandler,995;Alan Price,1008;Bo Diddley,1...",instagram;guitar international;youtube,"Instagram,2621;Guitar International,1455;Youtu...","Hilton Valentine,17;British Invasion,57;Rising..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
151925,20210201234500,whiznews.com,https://whiznews.com/2021/02/01/liverpool-fill...,NaN,NaN,NaN,1#Ecuador#EC#EC#-2#-77.5#EC;1#Japan#JA#JA#36#1...,1#Japan#JA#JA##36#138#JA#2136;1#New Zealand#NZ...,joe willock;jurgen klopp;jordan henderson;ozan...,"Joe Willock,2584;Jurgen Klopp,532;Jordan Hende...",major league soccer,"Major League Soccer,3600","Ozan Kabak,376;Jurgen Klopp,561;Joe Gomez,684;..."
151926,20210201234500,trinidadexpress.com,https://trinidadexpress.com/opinion/letters/la...,NaN,TAX_ETHNICITY;TAX_ETHNICITY_ASHANTI;KILL;MANMA...,"TAX_ETHNICITY_ASHANTI,12;MANMADE_DISASTER_IMPL...",NaN,NaN,linus f didier mt;andrea bharatt;ashanti riley,"Linus F Didier Mt,404;Andrea Bharatt,168;Ashan...",NaN,NaN,"Ashanti Riley,19;Andrea Bharatt,176"
151927,20210201234500,iheart.com,https://wfmf.iheart.com/content/2021-02-01-mil...,NaN,TAX_FNCACT;TAX_FNCACT_SINGER;TAX_ETHNICITY;TAX...,"MEDIA_SOCIAL,891;TAX_FNCACT_SINGER,98;TAX_FNCA...",NaN,NaN,miley cyru,"Miley Cyru,36",youtube,"Youtube,891","Miley Cyru,38;Mazzy Star,73;Into You,90;Tiny D..."
151928,20210201234500,iheart.com,https://magic1079.iheart.com/content/2021-02-0...,NaN,PUBLIC_TRANSPORT;TRIAL;TAX_WORLDFISH;TAX_WORLD...,"TRIAL,77;TAX_WORLDFISH_FISH,523;UNGP_FORESTS_R...",NaN,NaN,jessica simpson;nick lachey,"Jessica Simpson,15;Nick Lachey,394",NaN,NaN,"Jessica Simpson,16;Nick Lachey,410"
151929,20210201234500,couriermail.com.au,https://www.couriermail.com.au/entertainment/t...,NaN,TAX_ECON_PRICE;MEDIA_SOCIAL;TAX_FNCACT;TAX_FNC...,"MEDIA_MSM,1795;MEDIA_SOCIAL,594;TAX_ECON_PRICE...",NaN,NaN,greg norman;sonia kruger;rob riggle;matt shirv...,"Greg Norman,245;Greg Norman,618;Greg Norman,78...",twitter,"Twitter,594","Steve Price,25;Holey Moley,159;Sonia Kruger,18..."

In [9]:
df[df['1'].isnull()]

,1,3,4,5,7,8,9,10,11,12,13,14,23
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5222,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13382,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13383,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13384,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
147202,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
147203,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
147204,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
147205,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
147206,NaN,NaN,NaN,<PAGE_LINKS>https://katiecavuto.com/;https://s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [10]:
df[df['3'].isnull()]

,1,3,4,5,7,8,9,10,11,12,13,14,23
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5222,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13381,"Content By Slug,5376;HeartRadio Popular Podcas...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13382,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13383,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
147202,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
147203,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
147204,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
147205,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
147206,NaN,NaN,NaN,<PAGE_LINKS>https://katiecavuto.com/;https://s...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [11]:
df['1'] = pd.to_numeric(df['1'],errors='coerce')
df = df.drop(df[df['1'].isnull()].index, axis=0)
df = df.drop(df[df['3'].isnull()].index, axis=0)
df

,1,3,4,5,7,8,9,10,11,12,13,14,23
0,2.021020e+13,tass.com,https://tass.com/emergencies/1250941,NaN,TAX_FNCACT;TAX_FNCACT_CHILDREN;ARREST;CRISISLE...,"SOC_POINTSOFINTEREST_POLICE_STATIONS,314;TAX_F...","4#Moscow, Moskva, Russia#RS#RS48#55.7522#37.61...","4#Moscow, Moskva, Russia#RS#RS48#25106#55.7522...",olga yaroslavskaya,"Olga Yaroslavskaya,180",NaN,NaN,"Rights Commissioner Olga Yaroslavskaya,169"
1,2.021020e+13,observer-reporter.com,https://observer-reporter.com/publications/shl...,NaN,GENERAL_HEALTH;HEALTH_PANDEMIC;WB_635_PUBLIC_H...,"MANMADE_DISASTER_IMPLIED,1548;MANMADE_DISASTER...",1#Lebanon#LE#LE#33.833333#35.833333#LE,1#Lebanon#LE#LE##33.833333#35.833333#LE#2280,lindsey bricker,"Lindsey Bricker,1968",NaN,NaN,"Lindsey Bricker,2111;Sugar Sugar Scrub,2146;Me..."
2,2.021020e+13,jordantimes.com,http://jordantimes.com/news/local/ujs-css-tops...,NaN,EDUCATION;SOC_POINTSOFINTEREST;SOC_POINTSOFINT...,"TAX_FNCACT_DIRECTOR,1343;USPEC_POLICY1,769;USP...","4#Amman, (Jo11), Jordan#JO#JO11#31.95#35.9333#...",1#Jordan#JO#JO##31#36#JO#13;1#Jordan#JO#JO##31...,zaid eyadat,"Zaid Eyadat,1355",centre for strategic studies;university of jor...,"Centre For Strategic Studies,85;University Of ...","Strategic Studies,79;Middle East,231;North Afr..."
3,2.021020e+13,apnews.com,https://apnews.com/1ce7ac194ff97c882f2fe79eebb...,NaN,TAX_DISEASE;TAX_DISEASE_CANCER;WB_1406_DISEASE...,"MANMADE_DISASTER_RADIOACTIVE,975;ARMEDCONFLICT...","2#California, United States#US#USCA#36.17#-119...","3#Los Angeles, California, United States#US#US...",padraig duignan;frances gulland,"Padraig Duignan,2156;Frances Gulland,1230",u s marine mammal commission;university of cal...,"University Of California,1259;Marine Mammal Ce...","Los Angeles Times,361;Marine Mammal Center,515..."
4,2.021020e+13,wdiy.org,https://www.wdiy.org/post/hilton-valentine-fou...,NaN,NaN,NaN,"4#North Shields, North Tyneside, United Kingdo...","5#Northumberland, Northumberland, United Kingd...",chas chandler;alan price;bo diddley;germaine v...,"Chas Chandler,995;Alan Price,1008;Bo Diddley,1...",instagram;guitar international;youtube,"Instagram,2621;Guitar International,1455;Youtu...","Hilton Valentine,17;British Invasion,57;Rising..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
151925,2.021020e+13,whiznews.com,https://whiznews.com/2021/02/01/liverpool-fill...,NaN,NaN,NaN,1#Ecuador#EC#EC#-2#-77.5#EC;1#Japan#JA#JA#36#1...,1#Japan#JA#JA##36#138#JA#2136;1#New Zealand#NZ...,joe willock;jurgen klopp;jordan henderson;ozan...,"Joe Willock,2584;Jurgen Klopp,532;Jordan Hende...",major league soccer,"Major League Soccer,3600","Ozan Kabak,376;Jurgen Klopp,561;Joe Gomez,684;..."
151926,2.021020e+13,trinidadexpress.com,https://trinidadexpress.com/opinion/letters/la...,NaN,TAX_ETHNICITY;TAX_ETHNICITY_ASHANTI;KILL;MANMA...,"TAX_ETHNICITY_ASHANTI,12;MANMADE_DISASTER_IMPL...",NaN,NaN,linus f didier mt;andrea bharatt;ashanti riley,"Linus F Didier Mt,404;Andrea Bharatt,168;Ashan...",NaN,NaN,"Ashanti Riley,19;Andrea Bharatt,176"
151927,2.021020e+13,iheart.com,https://wfmf.iheart.com/content/2021-02-01-mil...,NaN,TAX_FNCACT;TAX_FNCACT_SINGER;TAX_ETHNICITY;TAX...,"MEDIA_SOCIAL,891;TAX_FNCACT_SINGER,98;TAX_FNCA...",NaN,NaN,miley cyru,"Miley Cyru,36",youtube,"Youtube,891","Miley Cyru,38;Mazzy Star,73;Into You,90;Tiny D..."
151928,2.021020e+13,iheart.com,https://magic1079.iheart.com/content/2021-02-0...,NaN,PUBLIC_TRANSPORT;TRIAL;TAX_WORLDFISH;TAX_WORLD...,"TRIAL,77;TAX_WORLDFISH_FISH,523;UNGP_FORESTS_R...",NaN,NaN,jessica simpson;nick lachey,"Jessica Simpson,15;Nick Lachey,394",NaN,NaN,"Jessica Simpson,16;Nick Lachey,410"
151929,2.021020e+13,couriermail.com.au,https://www.couriermail.com.au/entertainment/t...,NaN,TAX_ECON_PRICE;MEDIA_SOCIAL;TAX_FNCACT;TAX_FNC...,"MEDIA_MSM,1795;MEDIA_SOCIAL,594;TAX_ECON_PRICE...",NaN,NaN,greg norman;sonia kruger;rob riggle;matt shirv...,"Greg Norman,245;Greg Norman,618;Greg Norman,78...",twitter,"Twitter,594","Steve Price,25;Holey Moley,159;Sonia Kruger,18..."

In [12]:
df['1'] = [int(float(i)) for i in df['1']]
df

,1,3,4,5,7,8,9,10,11,12,13,14,23
0,20210201000000,tass.com,https://tass.com/emergencies/1250941,NaN,TAX_FNCACT;TAX_FNCACT_CHILDREN;ARREST;CRISISLE...,"SOC_POINTSOFINTEREST_POLICE_STATIONS,314;TAX_F...","4#Moscow, Moskva, Russia#RS#RS48#55.7522#37.61...","4#Moscow, Moskva, Russia#RS#RS48#25106#55.7522...",olga yaroslavskaya,"Olga Yaroslavskaya,180",NaN,NaN,"Rights Commissioner Olga Yaroslavskaya,169"
1,20210201000000,observer-reporter.com,https://observer-reporter.com/publications/shl...,NaN,GENERAL_HEALTH;HEALTH_PANDEMIC;WB_635_PUBLIC_H...,"MANMADE_DISASTER_IMPLIED,1548;MANMADE_DISASTER...",1#Lebanon#LE#LE#33.833333#35.833333#LE,1#Lebanon#LE#LE##33.833333#35.833333#LE#2280,lindsey bricker,"Lindsey Bricker,1968",NaN,NaN,"Lindsey Bricker,2111;Sugar Sugar Scrub,2146;Me..."
2,20210201000000,jordantimes.com,http://jordantimes.com/news/local/ujs-css-tops...,NaN,EDUCATION;SOC_POINTSOFINTEREST;SOC_POINTSOFINT...,"TAX_FNCACT_DIRECTOR,1343;USPEC_POLICY1,769;USP...","4#Amman, (Jo11), Jordan#JO#JO11#31.95#35.9333#...",1#Jordan#JO#JO##31#36#JO#13;1#Jordan#JO#JO##31...,zaid eyadat,"Zaid Eyadat,1355",centre for strategic studies;university of jor...,"Centre For Strategic Studies,85;University Of ...","Strategic Studies,79;Middle East,231;North Afr..."
3,20210201000000,apnews.com,https://apnews.com/1ce7ac194ff97c882f2fe79eebb...,NaN,TAX_DISEASE;TAX_DISEASE_CANCER;WB_1406_DISEASE...,"MANMADE_DISASTER_RADIOACTIVE,975;ARMEDCONFLICT...","2#California, United States#US#USCA#36.17#-119...","3#Los Angeles, California, United States#US#US...",padraig duignan;frances gulland,"Padraig Duignan,2156;Frances Gulland,1230",u s marine mammal commission;university of cal...,"University Of California,1259;Marine Mammal Ce...","Los Angeles Times,361;Marine Mammal Center,515..."
4,20210201000000,wdiy.org,https://www.wdiy.org/post/hilton-valentine-fou...,NaN,NaN,NaN,"4#North Shields, North Tyneside, United Kingdo...","5#Northumberland, Northumberland, United Kingd...",chas chandler;alan price;bo diddley;germaine v...,"Chas Chandler,995;Alan Price,1008;Bo Diddley,1...",instagram;guitar international;youtube,"Instagram,2621;Guitar International,1455;Youtu...","Hilton Valentine,17;British Invasion,57;Rising..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
151925,20210201234500,whiznews.com,https://whiznews.com/2021/02/01/liverpool-fill...,NaN,NaN,NaN,1#Ecuador#EC#EC#-2#-77.5#EC;1#Japan#JA#JA#36#1...,1#Japan#JA#JA##36#138#JA#2136;1#New Zealand#NZ...,joe willock;jurgen klopp;jordan henderson;ozan...,"Joe Willock,2584;Jurgen Klopp,532;Jordan Hende...",major league soccer,"Major League Soccer,3600","Ozan Kabak,376;Jurgen Klopp,561;Joe Gomez,684;..."
151926,20210201234500,trinidadexpress.com,https://trinidadexpress.com/opinion/letters/la...,NaN,TAX_ETHNICITY;TAX_ETHNICITY_ASHANTI;KILL;MANMA...,"TAX_ETHNICITY_ASHANTI,12;MANMADE_DISASTER_IMPL...",NaN,NaN,linus f didier mt;andrea bharatt;ashanti riley,"Linus F Didier Mt,404;Andrea Bharatt,168;Ashan...",NaN,NaN,"Ashanti Riley,19;Andrea Bharatt,176"
151927,20210201234500,iheart.com,https://wfmf.iheart.com/content/2021-02-01-mil...,NaN,TAX_FNCACT;TAX_FNCACT_SINGER;TAX_ETHNICITY;TAX...,"MEDIA_SOCIAL,891;TAX_FNCACT_SINGER,98;TAX_FNCA...",NaN,NaN,miley cyru,"Miley Cyru,36",youtube,"Youtube,891","Miley Cyru,38;Mazzy Star,73;Into You,90;Tiny D..."
151928,20210201234500,iheart.com,https://magic1079.iheart.com/content/2021-02-0...,NaN,PUBLIC_TRANSPORT;TRIAL;TAX_WORLDFISH;TAX_WORLD...,"TRIAL,77;TAX_WORLDFISH_FISH,523;UNGP_FORESTS_R...",NaN,NaN,jessica simpson;nick lachey,"Jessica Simpson,15;Nick Lachey,394",NaN,NaN,"Jessica Simpson,16;Nick Lachey,410"
151929,20210201234500,couriermail.com.au,https://www.couriermail.com.au/entertainment/t...,NaN,TAX_ECON_PRICE;MEDIA_SOCIAL;TAX_FNCACT;TAX_FNC...,"MEDIA_MSM,1795;MEDIA_SOCIAL,594;TAX_ECON_PRICE...",NaN,NaN,greg norman;sonia kruger;rob riggle;matt shirv...,"Greg Norman,245;Greg Norman,618;Greg Norman,78...",twitter,"Twitter,594","Steve Price,25;Holey Moley,159;Sonia Kruger,18..."

In [20]:
df = df[(df['3']=='yahoo.com') | (df['3']=='reuters.com') | (df['3']=='marketwatch.com') | (df['3']=='prnewswire.com')]
df

,1,3,4,5,7,8,9,10,11,12,13,14,23
47,20210201000000,reuters.com,https://www.reuters.com/article/us-myanmar-pol...,NaN,TAX_FNCACT;TAX_FNCACT_LEADER;USPEC_POLITICS_GE...,"IDEOLOGY,1198;GENERAL_GOVERNMENT,322;EPU_POLIC...","4#London, London, City Of, United Kingdom#UK#U...","4#London, London, City Of, United Kingdom#UK#U...",peter cooney;win myint;myo nyunt;suu kyi,"Peter Cooney,1143;Win Myint,516;Myo Nyunt,459;...",thomson reuters trust principles;national leag...,"Thomson Reuters Trust Principles,1198;National...","Aung San Suu Kyi,77;National League,221;Myo Ny..."
70,20210201000000,reuters.com,https://www.reuters.com/article/us-health-coro...,"KILL#19#means#2#New York, United States#US#USN...",TAX_ETHNICITY;TAX_ETHNICITY_BLACK;HEALTH_VACCI...,"IDEOLOGY,2113;MEDIA_MSM,733;HEALTH_VACCINATION...","2#New York, United States#US#USNY#42.1497#-74....","2#New Yorker, United States#US#USNY##42.1497#-...",anthony fauci;barbara goldberg;andrew cuomo;da...,"Anthony Fauci,1923;Barbara Goldberg,19;Barbara...",thomson reuters trust principles;reuters;unite...,"Thomson Reuters Trust Principles,2113;Reuters,...","New Yorker,69;United States,281;York Governor ..."
318,20210201000000,yahoo.com,https://news.yahoo.com/republican-adam-kinzing...,"KILL#5##2#Illinois, United States#US#USIL#40.3...",LEADER;TAX_FNCACT;TAX_FNCACT_CONGRESSMAN;USPEC...,"TAX_POLITICAL_PARTY_REPUBLICANS,148;TAX_POLITI...","2#Florida, United States#US#USFL#27.8333#-81.7...","2#Illinois, United States#US#USIL##40.3363#-89...",brian sicknick;donald trump;adam kinzinger;kev...,"Brian Sicknick,821;Donald Trump,180;Adam Kinzi...",republican party;us capitol police;republicans...,"Republican Party,2109;Us Capitol Police,796;Re...","Congressman Adam Kinzinger,27;Donald Trump,192..."
367,20210201000000,yahoo.com,https://news.yahoo.com/usc-could-uclas-jalen-h...,NaN,SOC_EMERGINGTECH;TAX_FNCACT;TAX_FNCACT_EXPLORE...,"TAX_FNCACT_NAVIGATOR,3847;TAX_FNCACT_NAVIGATOR...",NaN,NaN,NaN,NaN,yahoo,"Yahoo,1430",NaN
370,20210201000000,reuters.com,https://www.reuters.com/article/us-retail-trad...,NaN,ENV_METALS;WB_2937_SILVER;WB_507_ENERGY_AND_EX...,"IDEOLOGY,583;TAX_ECON_PRICE,65;TAX_FNCACT_MINE...",1#Australia#AS#AS#-25#135#AS;1#Singapore#SN#SN...,1#Australia#AS#AS##-25#135#AS#137;1#Singapore#...,tom westbrook;daniel wallis,"Tom Westbrook,501;Daniel Wallis,528",thomson reuters trust principles;reuters;argen...,"Thomson Reuters Trust Principles,583;Reuters,1...","Argent Minerals,444;Boab Metals,461;Investigat..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...
151796,20210201234500,marketwatch.com,https://www.marketwatch.com/press-release/dubb...,NaN,CRISISLEX_C07_SAFETY;UNGP_FORESTS_RIVERS_OCEAN...,"WB_652_ICT_APPLICATIONS,3242;WB_660_BUSINESS_I...","1#Australia#AS#AS#-25#135#AS;4#Melbourne, Vict...","2#Texas, United States#US#USTX##31.106#-97.647...",mike ammerlaan;asia pacific,"Mike Ammerlaan,2242;Asia Pacific,3146",ecosystem at microsoft corp;microsoft,"Ecosystem At Microsoft Corp,2297;Microsoft,382...","Unified Cloud Call Recording,330;Microsoft Azu..."
151827,20210201234500,reuters.com,https://www.reuters.com/article/us-usa-white-s...,NaN,TAX_FNCACT;TAX_FNCACT_REPRESENTATIVE;LEADER;TA...,"IDEOLOGY,1833;WB_2467_TERRORISM,1219;WB_2433_C...",1#United States#US#US#39.828175#-98.5795#US;3#...,"3#White House, District Of Columbia, United St...",lisa shumaker;donald trump;jackie speier;lloyd...,"Lisa Shumaker,1778;Donald Trump,1625;Jackie Sp...",thomson reuters trust principles;department of...,"Thomson Reuters Trust Principles,1833;Departme...","Jackie Speier,81;President Joe Biden,118;House..."
151853,20210201234500,reuters.com,https://www.reuters.com/article/us-mediatek-5g...,NaN,TAX_ETHNICITY;TAX_ETHNICITY_TAIWANESE;TAX_FNCA...,"IDEOLOGY,1607;TAX_FNCACT_DESIGNER,66;TAX_FNCAC...",1#China#CH#CH#35#105#CH;1#Taiwan#TW#TW#24#121#...,"4#Xiaomi, Fujian, China#CH#CH07#13163#25.2225#...",stephen nellis;finbarr moynihan,"Stephen Nellis,17;Stephen Nellis,1491;Finbarr ...",samsung electronics co ltd;thomson reuters tru...,"Samsung Electronics Co Ltd,227;Thomson Reuters...","MediaTek Inc,83;Qualcomm Inc,203;Samsung Elect..."
151881,20210201234500,marketwatch.com,https://www.marketwatch.com/story/biden-meets-...,KILL#450#nears#1#United States#US#US#39.828175...,LEADER;TAX_FNCACT;TAX_FNCACT_PRESIDENT;USPEC_P...,"RURAL,3742;TAX_POLITICAL_PARTY_REPUBLICANS,109...",1#United States#US#US#39.828175#-98.5795#US;2#...,"2#Kansas, United States#US#USKS##38.5111#-96.8...",shelley moore capito;todd young;mitt romney;na...,"Shelley Moore Capito,6275;Todd Young,6305;Mitt...",senate majority leader chuck schumer;senate de...,"Senate Majority Leader Chuck Schumer,1726;Sena...","President Joe Biden,32;Oval Office,364;Vice Pr..."
151904,20210201234500,prnewswire.com,https://www.prnewswire.com/news-releases/ironc...,NaN,WB_678_DIGITAL_GOVERNMENT;WB_652_ICT_APPLICATI...,"TAX_FNCACT_MANAGER,2836;WB_135_TRANSPORT,206;W...",NaN,NaN,patrick walsh,"Patrick Walsh,618",amazon web services;amazon simple storage serv...,"Amazon Web Services,468;Amazon Simple Storage ...","SaaS Shield,204;Amazon Simple Storage Service,..."

# EDA

## Generate website counts to determine how to filter

In [ ]:
websites = df.loc[:,'3']
#print(websites)

In [ ]:
# 50 most popular websites
websites.str.split(";",expand=True).stack().value_counts()[0:100]

In [ ]:
websites_df = websites.str.split(";",expand=True).stack().value_counts()[0:100].rename_axis('website').reset_index(name='counts')
websites_df

In [ ]:
websites_df.to_excel("website.xlsx")

iheart.com                 32071
msn.com                    16704
medium.com                  9739
reuters.com                 6849
indiatimes.com              5370
yahoo.com                   5367
prnewswire.com              4368
dailymail.co.uk             3807
apnews.com                  3542
texasguardian.com           3450
sandiegosun.com             3117
newyorktelegraph.com        3043
ianslive.in                 2719
marketwatch.com             2647
washingtontimes.com         2461
sfgate.com                  2452
chron.com                   2449
onenewspage.com             2256
tmcnet.com                  2250
thenews.com.pk              2157
investegate.co.uk           2137
freerepublic.com            1997
thehindu.com                1976
upstract.com                1935
business-standard.com       1793
lmtonline.com               1760
finanznachrichten.de        1749
express.co.uk               1729
cnet.com                    1720
chinadaily.com.cn           1697
prokerala.com               1575
bignewsnetwork.com          1573
thestar.com.my              1532
siouxcityjournal.com        1515
aninews.in                  1508
allafrica.com               1478
moneycontrol.com            1443
mirror.co.uk                1427
thetimes.co.uk              1336
patch.com                   1336
daijiworld.com              1330
ghanaweb.com                1318
timesnownews.com            1225
washingtonpost.com          1219
news18.com                  1211
princegeorgecitizen.com     1210
xinhuanet.com               1207
digitaljournal.com          1202
openpr.com                  1194
nzherald.co.nz              1193

## Generate keyword count

In [ ]:
keywords = df.loc[:,'5']
#print(keywords)

In [ ]:
# 100 most popular keywords
keywords_df = keywords.str.split("#",expand=True).stack().value_counts()[0:100].rename_axis('keywords').reset_index(name='counts')
keywords_df

In [ ]:
keywords_df.to_excel("keyword.xlsx")

## Generate topics count

In [ ]:
topics = df.loc[:,'7']
#print(topics)

In [ ]:
# 100 most populare topics
topics_df = topics.str.split(";",expand=True).stack().value_counts()[0:100].rename_axis('topics').reset_index(name='counts')
topics_df

In [ ]:
topics_df.to_excel("topic.xlsx")

## Convert datetime stamp

In [ ]:
date_time = df.loc[:,'1']
print(type(dt.strptime(date_time[len(date_time)], '%Y%m%d%H%M%S')))
print(dt.strptime(date_time[len(date_time)], '%Y%m%d%H%M%S'))

In [ ]:
df['1'] =[dt.strptime(str(d), '%Y%m%d%H%M%S') for d in date_time]
df