In [81]:
import pandas as pd
import time
from os.path import exists
# There are 2 tables on the Wikipedia page
# we want the first table

tables = pd.read_html('https://en.wikipedia.org/wiki/List_of_S%26P_500_companies')
sp500_df = tables[1]
sp500_df

                  Date  Added                       Removed                   \
                  Date Ticker              Security  Ticker         Security
0     February 3, 2022    NaN                   NaN     GPS              Gap
1     February 2, 2022    CEG  Constellation Energy     NaN              NaN
2    December 20, 2021   SBNY        Signature Bank     LEG  Leggett & Platt
3    December 20, 2021   SEDG             SolarEdge     HBI      Hanesbrands
4    December 20, 2021    FDS               FactSet      WU    Western Union
..                 ...    ...                   ...     ...              ...
284   December 5, 2000    SBL   Symbol Technologies      OI   Owens-Illinois
285   December 5, 2000    AYE      Allegheny Energy     GRA         WR Grace
286   December 5, 2000    ABK       Ambac Financial     CCK   Crown Holdings
287      July 27, 2000   JDSU          JDS Uniphase     RAD          RiteAid
288   December 7, 1999   YHOO                Yahoo!     LDW          Laidlaw

                                                Reason
                                                Reason
0                     Market capitalization change.[6]
1    S&P 500 and 100 constituent Exelon Corp. spun ...
2                     Market capitalization change.[7]
3                     Market capitalization change.[7]
4                     Market capitalization change.[7]
..                                                 ...
284                                Market Cap changes.
285                                Market Cap changes.
286                                Market Cap changes.
287                            Market Cap change.[223]
288                 Market capitalization change.[224]

[289 rows x 6 columns]

In [82]:
sp500_df.columns

MultiIndex([(   'Date',     'Date'),
            (  'Added',   'Ticker'),
            (  'Added', 'Security'),
            ('Removed',   'Ticker'),
            ('Removed', 'Security'),
            ( 'Reason',   'Reason')],
           )

In [83]:
sp500_df.shape

(289, 6)

In [84]:
sp500_df.columns = sp500_df.columns.droplevel()
sp500_df

,Date,Ticker,Security,Ticker,Security,Reason
0,"February 3, 2022",NaN,NaN,GPS,Gap,Market capitalization change.[6]
1,"February 2, 2022",CEG,Constellation Energy,NaN,NaN,S&P 500 and 100 constituent Exelon Corp. spun ...
2,"December 20, 2021",SBNY,Signature Bank,LEG,Leggett & Platt,Market capitalization change.[7]
3,"December 20, 2021",SEDG,SolarEdge,HBI,Hanesbrands,Market capitalization change.[7]
4,"December 20, 2021",FDS,FactSet,WU,Western Union,Market capitalization change.[7]
...,...,...,...,...,...,...
284,"December 5, 2000",SBL,Symbol Technologies,OI,Owens-Illinois,Market Cap changes.
285,"December 5, 2000",AYE,Allegheny Energy,GRA,WR Grace,Market Cap changes.
286,"December 5, 2000",ABK,Ambac Financial,CCK,Crown Holdings,Market Cap changes.
287,"July 27, 2000",JDSU,JDS Uniphase,RAD,RiteAid,Market Cap change.[223]
288,"December 7, 1999",YHOO,Yahoo!,LDW,Laidlaw,Market capitalization change.[224]

In [85]:
sp500_df.columns.values[1:3] = ['add_ticker', 'add_sec']
sp500_df.columns.values[3:5] = ['rm_ticker', 'rm_sec']
sp500_df

,Date,add_ticker,add_sec,rm_ticker,rm_sec,Reason
0,"February 3, 2022",NaN,NaN,GPS,Gap,Market capitalization change.[6]
1,"February 2, 2022",CEG,Constellation Energy,NaN,NaN,S&P 500 and 100 constituent Exelon Corp. spun ...
2,"December 20, 2021",SBNY,Signature Bank,LEG,Leggett & Platt,Market capitalization change.[7]
3,"December 20, 2021",SEDG,SolarEdge,HBI,Hanesbrands,Market capitalization change.[7]
4,"December 20, 2021",FDS,FactSet,WU,Western Union,Market capitalization change.[7]
...,...,...,...,...,...,...
284,"December 5, 2000",SBL,Symbol Technologies,OI,Owens-Illinois,Market Cap changes.
285,"December 5, 2000",AYE,Allegheny Energy,GRA,WR Grace,Market Cap changes.
286,"December 5, 2000",ABK,Ambac Financial,CCK,Crown Holdings,Market Cap changes.
287,"July 27, 2000",JDSU,JDS Uniphase,RAD,RiteAid,Market Cap change.[223]
288,"December 7, 1999",YHOO,Yahoo!,LDW,Laidlaw,Market capitalization change.[224]

In [106]:
add_df = sp500_df[['Date','add_ticker', 'add_sec', 'Reason']]
add_df = add_df.drop(add_df[add_df['add_ticker'].isnull()].index,axis=0)
add_df = add_df.rename(columns={'add_ticker': 'ticker', 'add_sec': 'security'})
add_df['action'] = 'add'
add_df

,Date,ticker,security,Reason,action
1,"February 2, 2022",CEG,Constellation Energy,S&P 500 and 100 constituent Exelon Corp. spun ...,add
2,"December 20, 2021",SBNY,Signature Bank,Market capitalization change.[7],add
3,"December 20, 2021",SEDG,SolarEdge,Market capitalization change.[7],add
4,"December 20, 2021",FDS,FactSet,Market capitalization change.[7],add
5,"December 14, 2021",EPAM,EPAM Systems,Canadian Pacific acquired Kansas City Southern...,add
...,...,...,...,...,...
284,"December 5, 2000",SBL,Symbol Technologies,Market Cap changes.,add
285,"December 5, 2000",AYE,Allegheny Energy,Market Cap changes.,add
286,"December 5, 2000",ABK,Ambac Financial,Market Cap changes.,add
287,"July 27, 2000",JDSU,JDS Uniphase,Market Cap change.[223],add
288,"December 7, 1999",YHOO,Yahoo!,Market capitalization change.[224],add

In [107]:
rm_df = sp500_df[['Date','rm_ticker', 'rm_sec', 'Reason']]
rm_df = rm_df.drop(rm_df[rm_df['rm_ticker'].isnull()].index,axis=0)
rm_df = rm_df.rename(columns={'rm_ticker': 'ticker', 'rm_sec': 'security'})
rm_df['action'] = 'remove'
rm_df

,Date,ticker,security,Reason,action
0,"February 3, 2022",GPS,Gap,Market capitalization change.[6],remove
2,"December 20, 2021",LEG,Leggett & Platt,Market capitalization change.[7],remove
3,"December 20, 2021",HBI,Hanesbrands,Market capitalization change.[7],remove
4,"December 20, 2021",WU,Western Union,Market capitalization change.[7],remove
5,"December 14, 2021",KSU,Kansas City Southern,Canadian Pacific acquired Kansas City Southern...,remove
...,...,...,...,...,...
284,"December 5, 2000",OI,Owens-Illinois,Market Cap changes.,remove
285,"December 5, 2000",GRA,WR Grace,Market Cap changes.,remove
286,"December 5, 2000",CCK,Crown Holdings,Market Cap changes.,remove
287,"July 27, 2000",RAD,RiteAid,Market Cap change.[223],remove
288,"December 7, 1999",LDW,Laidlaw,Market capitalization change.[224],remove

In [112]:
frames = [rm_df, add_df]
df = pd.concat(frames).sort_index()
df

,Date,ticker,security,Reason,action
0,"February 3, 2022",GPS,Gap,Market capitalization change.[6],remove
1,"February 2, 2022",CEG,Constellation Energy,S&P 500 and 100 constituent Exelon Corp. spun ...,add
2,"December 20, 2021",LEG,Leggett & Platt,Market capitalization change.[7],remove
2,"December 20, 2021",SBNY,Signature Bank,Market capitalization change.[7],add
3,"December 20, 2021",SEDG,SolarEdge,Market capitalization change.[7],add
...,...,...,...,...,...
286,"December 5, 2000",ABK,Ambac Financial,Market Cap changes.,add
287,"July 27, 2000",JDSU,JDS Uniphase,Market Cap change.[223],add
287,"July 27, 2000",RAD,RiteAid,Market Cap change.[223],remove
288,"December 7, 1999",LDW,Laidlaw,Market capitalization change.[224],remove
288,"December 7, 1999",YHOO,Yahoo!,Market capitalization change.[224],add